import type { Metadata } from "next";
import { Manrope, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import MainHeader from "@/components/homepage/MainHeader";

const manrope = Manrope({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.variable} ${geistMono.variable} antialiased`}>
        <MainHeader />
        <main className="max-w-[1180px] flex flex-col justify-center items-center gap-4 p-4 mx-auto">
          {children}
        </main>
      </body>
    </html>
  );
}
